### ISSUE TITLE
PDF: scroll horizontally

### ISSUE THREAD

**Issue by tobiasBora** [manateelazycat/emacs-application-framework#271] opened 2020-04-09 20:11 UTC
Hello,

First, thanks a lot for this amazing tool! I really hope it will go big! I just tried it and it's already awesome. It's still not perfect (I had some issues with the web browser after loading several pages it was very slow) but I guess it will improve soon.

One request I'd like to formulate is the following: when I `M-x eaf-open` a pdf, I cannot find how to scroll horizontally, nor with shortkeys or with my touchpad. It's quite annoying when reading some two-columns pdf. Could you fix that please?

Thanks a lot, and keep the god job!

**Comment by manateelazycat** [comment] 2020-04-10 02:12
Can you give me some example pdf?

I need test it and try to fix this issue.

Thanks for feedback!

**Comment by tobiasBora** [comment] 2020-04-10 18:55
Well, any pdf has the same issue, for example [this one](http://www.africau.edu/images/default/sample.pdf). Actually, in the help manual I cannot even find a binding to right/left scrolling:

```
C-n             eaf-proxy-scroll_up
C-p             eaf-proxy-scroll_down
```

**Comment by manateelazycat** [comment] 2020-04-10 19:37
IMO, EAF PDF Viewer will scale any PDF fit screen width.

Can you give me some two column pdf that EAF can't handle it?

I can't reproduce your problem.

**Comment by lcabrini** [comment] 2020-04-10 22:17
I guess I'm also running into this problem and in my case it is not a two column page. I normally keep two window side by side, one is the PDF and one is for taking notes. The PDF is about that Japanese language and the default font size is way too small for my old, tired eyes. So I zoom.

Now I can move up and down in the document, but it seems not left and right. At least I didn't figure it out yet. I also have PDF Tools installed, so I use that instead when I need horizontal scrolling.

**Comment by manateelazycat** [comment] 2020-04-11 01:55
> I guess I'm also running into this problem and in my case it is not a two column page. I normally keep two window side by side, one is the PDF and one is for taking notes. The PDF is about that Japanese language and the default font size is way too small for my old, tired eyes. So I zoom.
> 
> Now I can move up and down in the document, but it seems not left and right. At least I didn't figure it out yet. I also have PDF Tools installed, so I use that instead when I need horizontal scrolling.

I see.

@luhuaei Can you help me add this feature?

**Comment by luhuaei** [comment] 2020-04-11 02:13
I have a try :smile:

**Comment by MatthewZMD** [comment] 2020-04-11 05:07
Issue should be fixed in latest commit

**Closed** 2020-04-11 05:06 UTC

**Comment by tobiasBora** [comment] 2020-04-11 19:24
Thanks for the commit. It fixes the issue partially, but may I ask to reopen this issue a bit longer for two reasons:
1) the name scroll-left and scroll-right are inverted (you would expect `C-f` to go forward (so to the right), and it's indeed called `eaf-proxy-scroll_right`, but it scrolls to the left).
2) the touchpad scroll does not work.

**Comment by MatthewZMD** [comment] 2020-04-12 02:50
I personally haven't test it myself, but @luhuaei has a new patch to fix it

**Comment by tobiasBora** [comment] 2020-04-12 09:29
Thanks for the commit. It fixes the key shortcuts, but with the mouse scrolling there are two issues:

1. the horizontal scrolling is not smooth like the vertical scrolling
2. for some reason the horizontal scrolling was reset when moving vertically

I created a push request that fixes the two issues here https://github.com/manateelazycat/emacs-application-framework/pull/274.
