### ISSUE TITLE
EAF not capturing keyboard events on WMs such as i3, sway, etc.

### ISSUE THREAD

**Issue by legalnonsense** [manateelazycat/emacs-application-framework#237] opened 2020-02-13 14:15 UTC
I installed via AUR. Using Manjaro with emacs 26.3. 

None of the EAF apps (including emacs itself) are getting keyboard events when running the demo, web browser, or pdf viewer. I haven't tried others. These apps will respond to mouse events only. Problem persists with emacs -q. 

Happy to provide more info but do not know what to provide at this point.

**Comment by manateelazycat** [comment] 2020-02-13 14:17
Which desktop environment do you use?

I haven't use emacs-eaf aur package, I can not guarantee it will be able to work.

**Comment by MatthewZMD** [comment] 2020-02-13 14:33
That's right, emacs-aur is made possible by the community, we personally do not have the chance to use it yet.

**Comment by legalnonsense** [comment] 2020-02-13 14:35
I also installed previously manually, so AUR not the isue. 

Using i3 as my wm. I will reboot to XFCE and see if it works.

**Comment by legalnonsense** [comment] 2020-02-13 14:37
Okay - works when I use XFCE, so I am guessing there is a problem with i3. Happy to provide any other info I can. Would love to get this working as it's something I anticipate using a great deal.

**Comment by MatthewZMD** [comment] 2020-02-13 14:49
Great to hear it works at least on xfce for you. The challange we have right now to support EAF on more DEs and platforms is that we don't use them ourselves. It would be best if you can play around with EAF on i3 to get familiar with it and contribute :)

**Comment by legalnonsense** [comment] 2020-02-13 14:52
I am afraid I would not even know where to begin. I know some elisp and that is about it as far as programming goes. Hopefully someone else will see this and jump on it. I'll play around with it if I get any ideas though. This looks like an amazing package and thank you for putting it out there.

**Comment by manateelazycat** [comment] 2020-02-14 07:29
I search emacs-china forum, when you move cursor out of EAF area, i3wm will focus EAF buffer.

I think it's a bug of i3wm on focus handle.

**Comment by legalnonsense** [comment] 2020-02-14 12:38
Tried it and that makes it work. Not a huge inconvenience since I rarely use the mouse anyway. Thank you for reporting back.

**Comment by manateelazycat** [comment] 2020-02-16 08:06
It's bug of i3wm, not EAF, close issue.

**Comment by michaelmrose** [comment] 2020-06-03 20:33
Your app not working in i3wm doesn't mean it is a bug in i3wm

**Comment by manateelazycat** [comment] 2020-08-18 05:27
@legalnonsense i3 have many dirty patch to modify X11 reparent protocol, make EAF can't reparent Qt window with standard X11 protocol.

Anyway commuity developer commit workaround patch https://github.com/manateelazycat/emacs-application-framework/commit/2ff25cd6305fd01987766bbce49922b11020eed3 to fix this issue.

**Comment by enderger** [comment] 2020-09-27 18:48
i think I've found part of the problem. While reading EAF's source, I found this line:
```elisp
(defcustom eaf-wm-focus-fix-wms `("i3")
  "Set mouse cursor to frame bottom in these wms, to make EAF receive input event.
Add $DESKTOP_SESSION environment variable to this list."
  :type 'list
  :group 'eaf)
```
By changing the value of `eaf-wm-focus-fix-wms` to `(), I was able to restore keybinding functionality so long as I hover over the modeline for the frame. It appears as though the issue is linked to said variable.

**Comment by MatthewZMD** [comment] 2020-09-27 20:08
> handle the keybindings on the Python side, since it seems to handle keyboard inputs perfectly.

Python side does not handle keyboard inputs by design, so it never able to handle keyboard inputs perfectly.

Please edit your comment to clarify what exactly is different by modifying the eaf-wm-focus-fix-wms variable.

**Comment by io12** [comment] 2020-09-30 05:43
Is it worth adding a notice to the README about this? I use i3 and was confused why EAF was having focusing issues, but it was hard to find this GitHub issue since it's closed.

**Comment by MatthewZMD** [comment] 2020-09-30 07:30
It's worth reopening since 2ff25cd clearly did not fix this issue.

As a sanity check, what is the value of `echo $DESKTOP_SESSION` on your systems? Is it `i3`?

**Comment by io12** [comment] 2020-09-30 10:01
`DESKTOP_SESSION` is empty for me. It might only apply to desktop environments and not WMs like `i3`. I can set `DESKTOP_SESSION` manually tomorrow to see if the unfocusing patch works.

**Comment by enderger** [comment] 2020-09-30 21:51
Has anyone tested this on any other tiling WMs? Perhaps it is caused by the tiling nature of I3. Also to note, the code that I sent appears to never trigger, as the warning text never appeared in messages for the tool it uses even when missing. Finally, a better way to detect I3 would be to try to send the window manager a message (like the one used for logging out). I know there is a command for it but I can’t remember it’s name. That would also cover forks like i3-gaps.

**Comment by io12** [comment] 2020-10-06 06:13
> Has anyone tested this on any other tiling WMs? Perhaps it is caused by the tiling nature of I3.

I tested with [dwm](https://dwm.suckless.org/) just now, and it seems to work. This is probably more of an i3 problem than a tiling window manager problem.

**Comment by io12** [comment] 2020-10-06 06:20
Also, I tried hardcoding `DESKTOP_SESSION` to test if the i3 fix works otherwise. It definitely helps a lot, but if the browser window manages to grab focus (through mouse clicks, or because it was just opened), it doesn't ever release the focus and the problem still happens.

**Comment by manateelazycat** [comment] 2020-10-11 08:59
I think it's i3 problem that not follow WM protocol standard, and many i3 believer think it's a bug of EAF.

The "move to minibuffer" patch is hacking way.

I believe right way is i3 fix focus problem, or use i3 focus message instead hacking patch.

**Comment by manateelazycat** [comment] 2020-10-21 14:48
Close this issue since EAF can't adaptable to all window managers, sorry.

**Comment by io12** [comment] 2020-10-25 09:46
If this is a bug in i3, any ideas which part of the i3 code has the bug?

Also, if this issue is closed, it might make sense to add that EAF doesn't work with i3 to the README. When I first tried EAF, I couldn't easily find this issue since it was closed, so I was confused why it wasn't working.

**Comment by MatthewZMD** [comment] 2020-10-25 23:23
Let's keep it open, I don't see any reason for EAF not to adapt to i3 in the future.

**Comment by edgar-vincent** [comment] 2020-11-19 23:44
I don't know if it's actually the same bug, but I have exactly the same behaviour with Sway. The problem doesn't occur with LXQt.

**Comment by manateelazycat** [comment] 2020-11-26 11:05
Can you try newest version?

I have fix issue about Alt + Tab focus problem. Don't know this patch will fix i3?

**Comment by io12** [comment] 2020-11-28 08:48
I can still reproduce the issue with the new version.

Also, the Alt+Tab patch seems to create another issue in i3. When I have two workspaces open with emacs in both the first and second workspace, pressing Alt or Meta switches to the second workspace.

**Comment by PalaceChan** [comment] 2020-11-29 23:46
Just ran into this as well and took me a bit to find that it was because I use i3 as a window manager. Would it make sense to add in the README? Looking into switching to openbox window manager to see if that works with EAF - is there a list of known window managers that work?

**Comment by MatthewZMD** [comment] 2020-11-30 01:13
> is there a list of known window managers that work?

It is known to work nicely with desktop environments like Gnome and KDE

**Comment by manateelazycat** [comment] 2020-12-01 05:56
> I can still reproduce the issue with the new version.
> 
> Also, the Alt+Tab patch seems to create another issue in i3. When I have two workspaces open with emacs in both the first and second workspace, pressing Alt or Meta switches to the second workspace.

Well, I have disable Alt+Tab patch when EAF found it running under i3.

**Comment by fredefox** [comment] 2020-12-06 12:59
It appears that keys are handled differently depending on which window has focus. I suspect it is not WM specific (I happen to be using i3 as some other in this thread). In i3 the window usually gains focus when you hover it. I wonder if you'd be able to reproduce some of the same issues in other WMs, if you manage to focus the window displaying the QT5 application. Perhaps some other mechanism is preventing this from happening when you click it?

I noticed a thing which I think is relevant here and may help investigation: If I open a website in EAF and focus an input field. If I then hit escape I expect the input field to "blur" (web parlance for loose focus). This only happens, however, if my mouse is over the EAF buffer displaying the browser window. If I mouse over another buffer in my Emacs window the text "<es" is inserted into the input field. Very strange... The unfortunate thing about this is, that it if you move your mouse away from the EAF window you can use the EAF keybindings but not the QT5 key bindings and vice versa.

**Comment by manateelazycat** [comment] 2020-12-06 14:28
I post newest patch: https://github.com/manateelazycat/emacs-application-framework/commit/95e1de99ba2fe3ae6074f857094466d77f477b2b

I found the following law happend in KDE, i3 and qtile:
1. If the mouse is in the EAF window area, then switch back to Emacs, Emacs cannot get the input focus. (Cause by QEvent.ShortcutOverride)
2. If the mouse is out of EAF window area, then switch back to Emacs, Emacs can get the input focus.

So newest patch fix focus by below logic:
1. Call elisp function eaf-move-mouse-to-frame-bottom when switch back to Emacs. (Test with QTile)
2. Or use wmctrl activate on Emacs window after Alt + Tab operation. (Test with KDE)

I have test QTile, can you guys help me confirm this fix?
Thanks!

**Comment by edgar-vincent** [comment] 2020-12-06 16:36
Thanks!
It does not work under Sway, but this might be linked to Wayland support: #449

**Comment by manateelazycat** [comment] 2020-12-06 23:15
> Thanks!
> It does not work under Sway, but this might be linked to Wayland support: #449

can you help test i3?

**Comment by edgar-vincent** [comment] 2020-12-06 23:43
I just installed i3 to try it out. Unfortunately, it doesn't work.
Let me know if I can be of any help.

**Comment by manateelazycat** [comment] 2020-12-07 06:16
> I just installed i3 to try it out. Unfortunately, it doesn't work.
> Let me know if I can be of any help.

I see, I just install i3 and test it, not work because DESKTOP_SESSION should be /usr/share/xsessions/i3, is not i3.

I have post new patch to fix this:
https://github.com/manateelazycat/emacs-application-framework/commit/c40bd2a60cfce5a23a0f3c2f7f05441134839de7

I believe i3 will works well now.

Sway maybe casue by Wayland native technology, EAF has support XWayland.

Please re-open this issue if anyone found new bug on i3.

**Closed by manateelazycat** 2020-12-07 06:16 UTC
Labels: help wanted

**Comment by edgar-vincent** [comment] 2020-12-08 00:14
It doesn't seem to work here under i3, but maybe there's something wrong with my config.

**Comment by manateelazycat** [comment] 2020-12-08 00:25
> It doesn't seem to work here under i3, but maybe there's something wrong with my config.

i test standard i3 with default config

**Comment by io12** [comment] 2020-12-17 09:49
I can also still reproduce the bug.

**Comment by MatthewZMD** [comment] 2020-12-17 14:45
> I can also still reproduce the bug.

Are you on i3? Can you paste your $DESKTOP_SESSION value?

**Comment by io12** [comment] 2020-12-19 04:42
> Are you on i3? Can you paste your $DESKTOP_SESSION value?
I'm on i3 and DESKTOP_SESSION is not a set environment variable.

**Comment by manateelazycat** [comment] 2020-12-19 05:27
Can you set your DESKTOP_SESSION to string "i3" and try again?

**Comment by manateelazycat** [comment] 2020-12-19 05:38
> > Are you on i3? Can you paste your $DESKTOP_SESSION value?
> 
> I'm on i3 and DESKTOP_SESSION is not a set environment variable.

What's your value of XDG_CURRENT_DESKTOP ?

**Comment by io12** [comment] 2020-12-20 23:29
> What's your value of XDG_CURRENT_DESKTOP ?

That's also not set.

> Can you set your DESKTOP_SESSION to string "i3" and try again?

This works much better than EAF has ever worked on i3 before! The cursor jumps to the bottom-left corner, which isn't ideal, but at least the workaround works.

**Comment by io12** [comment] 2020-12-20 23:32
About how to test if i3 is running, you could check if there's a process called `i3` running or check if `xprop -root` contains `_NET_WM_NAME(UTF8_STRING) = "i3"`.

**Comment by manateelazycat** [comment] 2020-12-21 01:44
@io12 I see, I believe that the previous I3 users are because the DESKTOP_SESSION variables are not set.

Anyway, I post newest commit https://github.com/manateelazycat/emacs-application-framework/commit/c5fdf0bff2e2adc1a58bde002277f789985a31ef

That use command `wmctrl -m' get desktop name dynamically, not need set DESKTOP_SESSION anymore.

I believe i3 will works if user install wmctrl.

**Comment by io12** [comment] 2020-12-21 02:28
> @io12 I see, I believe that the previous I3 users are because the DESKTOP_SESSION variables are not set.

I remember manually setting DESKTOP_SESSION a lot earlier in the thread and it not working, so it must have been some recent change. https://github.com/manateelazycat/emacs-application-framework/issues/237#issuecomment-704056150

> I believe i3 will works if user install wmctrl.

Here's my `wmctrl -m` output:

```
Name: i3
Class: N/A
PID: N/A
Window manager's "showing the desktop" mode: N/A
```

**Comment by manateelazycat** [comment] 2020-12-21 02:37
> > @io12 I see, I believe that the previous I3 users are because the DESKTOP_SESSION variables are not set.
> 
> I remember manually setting DESKTOP_SESSION a lot earlier in the thread and it not working, so it must have been some recent change. [#237 (comment)](https://github.com/manateelazycat/emacs-application-framework/issues/237#issuecomment-704056150)
> 
> > I believe i3 will works if user install wmctrl.
> 
> Here's my `wmctrl -m` output:
> 
> ```
> Name: i3
> Class: N/A
> PID: N/A
> Window manager's "showing the desktop" mode: N/A
> ```

Please update to newest version, if you has install wmctrl and xdotool, EAF should work out of box now.

**Comment by io12** [comment] 2020-12-21 02:47
> Please update to newest version, if you has install wmctrl and xdotool, EAF should work out of box now.

It works now. Thank you!

**Comment by Jdogzz** [comment] 2021-01-01 06:04
I've been having the same issue using something more exotic and I'm happy to open a separate issue if that is preferred. I run emacs as a daemon on a remote server, launch emacsclient on a display, and access that display through the utility xpra (for now it's just the single emacs window) from my Windows computer. I have installed wmctrl and xdotool both installed. Here's my `wmctrl -m` output:

```
Name: Xpra
Class: N/A
PID: 543
Window manager's "showing the desktop" mode: N/A
```

I can input keystrokes to the eaf window (for example a PDF) only when I click in the minibuffer first. Clicking around in the eaf window directly will then again result in no keystrokes being detected.

**Comment by manateelazycat** [comment] 2021-01-01 06:30
> I've been having the same issue using something more exotic and I'm happy to open a separate issue if that is preferred. I run emacs as a daemon on a remote server, launch emacsclient on a display, and access that display through the utility xpra (for now it's just the single emacs window) from my Windows computer. I have installed wmctrl and xdotool both installed. Here's my `wmctrl -m` output:
> 
> ```
> Name: Xpra
> Class: N/A
> PID: 543
> Window manager's "showing the desktop" mode: N/A
> ```
> 
> I can input keystrokes to the eaf window (for example a PDF) only when I click in the minibuffer first. Clicking around in the eaf window directly will then again result in no keystrokes being detected.

can you add Xpra to list eaf-wm-focus-fix-wms, and try again?

**Comment by Jdogzz** [comment] 2021-01-01 15:43
That seems to have fixed it, thank you very much.

**Comment by QiangF** [comment] 2021-07-26 15:33
@manateelazycat The mouse cursor movement hack may defer users that need to use the mouse sometimes, I would suggest a better solution:

If my understanding is correct, eaf includes 2 part,  the gui as we see and the underlying emacs frame, if you can make the emacs frame  send fake keys to the gui part,  sure you can let the gui send keys to emacs.

When the gui receives a keyboard event,  do a check to see if the mouse pointer is above the gui, if so, the key must have not been processed by emacs, let the gui part send the key to emacs, emacs will look up the keybinding table, and execute the corresponding commands,.

If that command is to send a modified key event,  let the command also send a suppress signal that suppressed the key event origin check to the gui, and tell the gui that please don't send the key back again. If the mouse pointer is at the corner, or any where the window manager won't misbehave, let the gui just accept the key and don't bother emacs.

If that command has nothing to do with key event, no further action is needed.

I hope someone can get this to work and stop the mouse jumping madness.

**Comment by manateelazycat** [comment] 2021-07-26 22:38
> @manateelazycat The mouse cursor movement hack may defer users that need to use the mouse sometimes, I would suggest a better solution:
> 
> If my understanding is correct, eaf includes 2 part, the gui as we see and the underlying emacs frame, if you can make the emacs frame send fake keys to the gui part, sure you can let the gui send keys to emacs.
> 
> When the gui receives a keyboard event, do a check to see if the mouse pointer is above the gui, if so, the key must have not been processed by emacs, let the gui part send the key to emacs, emacs will look up the keybinding table, and execute the corresponding commands,.
> 
> If that command is to send a modified key event, let the command also send a suppress signal that suppress the key event origin check to the gui, and tell the gui that please don't send the key back again. If the mouse pointer is at the corner, or any where the window manager won't misbehave, let the gui just accept the key and don't bother emacs.
> 
> If that command has nothing to do with key event, no further action is needed.
> 
> I hope someone can get this to work and stop the mouse jumping madness.

NO，reason is focus problem of wm implemention
