### ISSUE TITLE
eaf-monitor-configuration-change hook breaks some keyboard macros

### ISSUE THREAD

**Issue by dnlopez** [manateelazycat/emacs-application-framework#207] opened 2020-01-27 03:37 UTC
Hi,

If I try to use some kinds of keyboard macros - in particular, it seems to be in cases where the macro prompts for any input in the minibuffer - after using EAF, Emacs hangs.

For example, I record a simple keyboard macro by pressing the following keys (doing an eval-expression followed by the input "123")

F3 M-: 1 2 3 RET F4

Then when I press F4 again to run the macro, it freezes until I press Ctrl-G. If I do toggle-debug-on-quit beforehand then I get this backtrace:

```
Debugger entered--Lisp error: (quit)
  dbus-call-method(:session "com.lazycat.eaf" "/com/lazycat/eaf" "com.lazycat.eaf" "update_views" "")
  apply(dbus-call-method :session "com.lazycat.eaf" "/com/lazycat/eaf" "com.lazycat.eaf" "update_views" "")
  eaf-call("update_views" "")
  (let (view-infos) (let ((--dolist-tail-- (frame-list))) (while --dolist-tail-- (let ((frame (car --dolist-tail--))) (let ((--dolist-tail-- (window-list frame))) (while --dolist-tail-- (let ((window (car --dolist-tail--))) (let ((buffer (window-buffer window))) (save-current-buffer (set-buffer buffer) (if (derived-mode-p 'eaf-mode) (let* ((window-allocation (eaf-get-window-allocation window)) (x (nth 0 window-allocation)) (y (nth 1 window-allocation)) (w (nth 2 window-allocation)) (h (nth 3 window-allocation))) (setq view-infos (cons (format "%s:%s:%s:%s:%s:%s" eaf--buffer-id (eaf-get-emacs-xid frame) x y w h) view-infos)))))) (setq --dolist-tail-- (cdr --dolist-tail--))))) (setq --dolist-tail-- (cdr --dolist-tail--))))) (eaf-call "update_views" (mapconcat (function identity) view-infos ",")))
  (progn (let (view-infos) (let ((--dolist-tail-- (frame-list))) (while --dolist-tail-- (let ((frame (car --dolist-tail--))) (let ((--dolist-tail-- (window-list frame))) (while --dolist-tail-- (let ((window (car --dolist-tail--))) (let ((buffer (window-buffer window))) (save-current-buffer (set-buffer buffer) (if (derived-mode-p 'eaf-mode) (let* ((window-allocation (eaf-get-window-allocation window)) (x (nth 0 window-allocation)) (y (nth 1 window-allocation)) (w (nth 2 window-allocation)) (h (nth 3 window-allocation))) (setq view-infos (cons (format "%s:%s:%s:%s:%s:%s" eaf--buffer-id (eaf-get-emacs-xid frame) x y w h) view-infos)))))) (setq --dolist-tail-- (cdr --dolist-tail--))))) (setq --dolist-tail-- (cdr --dolist-tail--))))) (eaf-call "update_views" (mapconcat (function identity) view-infos ","))))
  (condition-case nil (progn (let (view-infos) (let ((--dolist-tail-- (frame-list))) (while --dolist-tail-- (let ((frame (car --dolist-tail--))) (let ((--dolist-tail-- (window-list frame))) (while --dolist-tail-- (let ((window (car --dolist-tail--))) (let ((buffer (window-buffer window))) (save-current-buffer (set-buffer buffer) (if (derived-mode-p 'eaf-mode) (let* ((window-allocation (eaf-get-window-allocation window)) (x (nth 0 window-allocation)) (y (nth 1 window-allocation)) (w (nth 2 window-allocation)) (h (nth 3 window-allocation))) (setq view-infos (cons (format "%s:%s:%s:%s:%s:%s" eaf--buffer-id (eaf-get-emacs-xid frame) x y w h) view-infos)))))) (setq --dolist-tail-- (cdr --dolist-tail--))))) (setq --dolist-tail-- (cdr --dolist-tail--))))) (eaf-call "update_views" (mapconcat (function identity) view-infos ",")))) (error nil))
  (progn (condition-case nil (progn (let (view-infos) (let ((--dolist-tail-- (frame-list))) (while --dolist-tail-- (let ((frame (car --dolist-tail--))) (let ((--dolist-tail-- (window-list frame))) (while --dolist-tail-- (let ((window (car --dolist-tail--))) (let ((buffer (window-buffer window))) (save-current-buffer (set-buffer buffer) (if (derived-mode-p 'eaf-mode) (let* ((window-allocation (eaf-get-window-allocation window)) (x (nth 0 window-allocation)) (y (nth 1 window-allocation)) (w (nth 2 window-allocation)) (h (nth 3 window-allocation))) (setq view-infos (cons (format "%s:%s:%s:%s:%s:%s" eaf--buffer-id (eaf-get-emacs-xid frame) x y w h) view-infos)))))) (setq --dolist-tail-- (cdr --dolist-tail--))))) (setq --dolist-tail-- (cdr --dolist-tail--))))) (eaf-call "update_views" (mapconcat (function identity) view-infos ",")))) (error nil)))
  (if (process-live-p eaf-process) (progn (condition-case nil (progn (let (view-infos) (let ((--dolist-tail-- (frame-list))) (while --dolist-tail-- (let ((frame (car --dolist-tail--))) (let ((--dolist-tail-- (window-list frame))) (while --dolist-tail-- (let ((window (car --dolist-tail--))) (let ((buffer (window-buffer window))) (save-current-buffer (set-buffer buffer) (if (derived-mode-p 'eaf-mode) (let* ((window-allocation (eaf-get-window-allocation window)) (x (nth 0 window-allocation)) (y (nth 1 window-allocation)) (w (nth 2 window-allocation)) (h (nth 3 window-allocation))) (setq view-infos (cons (format "%s:%s:%s:%s:%s:%s" eaf--buffer-id (eaf-get-emacs-xid frame) x y w h) view-infos)))))) (setq --dolist-tail-- (cdr --dolist-tail--))))) (setq --dolist-tail-- (cdr --dolist-tail--))))) (eaf-call "update_views" (mapconcat (function identity) view-infos ",")))) (error nil))))
  eaf-monitor-configuration-change()
  read-from-minibuffer("Eval: " nil (keymap (9 . completion-at-point) (27 keymap (9 . completion-at-point)) keymap (menu-bar keymap (minibuf "Minibuf" keymap (previous menu-item "Previous History Item" previous-history-element :help "Put previous minibuffer history element in the minibuffer") (next menu-item "Next History Item" next-history-element :help "Put next minibuffer history element in the minibuffer") (isearch-backward menu-item "Isearch History Backward" isearch-backward :help "Incrementally search minibuffer history backward") (isearch-forward menu-item "Isearch History Forward" isearch-forward :help "Incrementally search minibuffer history forward") (return menu-item "Enter" exit-minibuffer :key-sequence "\015" :help "Terminate input and exit minibuffer") (quit menu-item "Quit" abort-recursive-edit :help "Abort input and exit minibuffer") "Minibuf")) (10 . exit-minibuffer) (13 . exit-minibuffer) (7 . abort-recursive-edit) (C-tab . file-cache-minibuffer-complete) (9 . self-insert-command) (XF86Back . previous-history-element) (up . previous-line-or-history-element) (prior . previous-history-element) (XF86Forward . next-history-element) (down . next-line-or-history-element) (next . next-history-element) (27 keymap (114 . previous-matching-history-element) (115 . next-matching-history-element) (112 . previous-history-element) (110 . next-history-element))) t read-expression-history)
  read--expression("Eval: ")
  byte-code("\301\302!\303\010!B\207" [current-prefix-arg read--expression "Eval: " eval-expression-get-print-arguments] 3)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)
  call-last-kbd-macro(nil kmacro-loop-setup-function)
  kmacro-call-macro(nil nil)
  kmacro-end-or-call-macro(nil)
  funcall-interactively(kmacro-end-or-call-macro nil)
  call-interactively(kmacro-end-or-call-macro nil nil)
  command-execute(kmacro-end-or-call-macro)
```

So it's getting stuck for some reason in dbus-call-method, called from eaf-monitor-configuration-change. If I do a (remove-hook 'window-configuration-change-hook #'eaf-monitor-configuration-change) then I can run the macro normally.

As mentioned, it doesn't happen with all macros, but just ones which take input from the minibuffer, as far as I can tell - so eg. anything with M-x, or C-x C-f to open a file, will also hang.

Tested on Emacs 26.1 on Arch Linux with a minimal "emacs -q" kind of startup.

**Comment by MatthewZMD** [comment] 2020-01-27 05:51
I cannot reproduce your exact error trace with `F3 M-: 1 2 3 RET F4` because `1 2 3` itself is invalid lisp syntax so `M-: 1 2 3` gives an error already.

However I do see the problem that almost every keyboard macro hangs EAF until `C-g`.. I will have a look.

**Comment by manateelazycat** [comment] 2020-01-27 18:53
@MatthewZMD You can remove ignore-errors from eaf-monitor-configuration-change function and try again.

**Comment by manateelazycat** [comment] 2020-01-28 04:44
I can reproduce this issue, but i still know how to fix this issue.

Thanks for report!

**Comment by MatthewZMD** [comment] 2020-01-28 05:12
I am still unable to reproduce from my side...

**Comment by manateelazycat** [comment] 2020-02-27 15:49
Keyboard macro support is not the plan of this project.

I will close this issue, sorry.

**Closed by manateelazycat** 2020-02-27 15:49 UTC
Labels: bug

**Comment by zbelial** [comment] 2020-10-11 03:07
Hi @dnlopez , sorry to bother you.
In case that you're still using EAF, could you please install the change [here](https://github.com/manateelazycat/emacs-application-framework/issues/408#issuecomment-706569044) in issue #408 and make another test? thanks. 
In summary, what you need to do is:
1. update EAF to the latest
2. add a new function in eaf.el 
```elisp
(defun eaf-call-async (method handler &rest args)
  "Call EAF Python process using `dbus-call-method' with METHOD and ARGS."
  (apply #'dbus-call-method-asynchronously
                       :session     ; use the session (not system) bus
                       "com.lazycat.eaf"  ; service name
                       "/com/lazycat/eaf" ; path name
                       "com.lazycat.eaf"  ; interface name
                       method
                       handler
                       :timeout 1000000
                       args)
    )
```
3. modify `eaf-monitor-configuration-change` to call `eaf-call-async` instead
```elisp
(eaf-call-async "update_views" nil (mapconcat #'identity view-infos ","))
```
4. restart Emacs and make some test

**Comment by dnlopez** [comment] 2020-10-11 15:04
Hi @zbelial ,

Yes, this fixes the issue that I had in this bug report. Thanks!
