### ISSUE TITLE
Cannot send keybindings  in EAF buffers

### ISSUE THREAD

**Issue by enderger** [manateelazycat/emacs-application-framework#405] opened 2020-09-26 23:17 UTC
**Describe the bug**
All EAF buffers are refusing to accept any keybindings. I can interact with the screen fine, but none of the navigational keys work

**To Reproduce**
1. Open the EAF web browser (or any other EAF app)
2. Try to send it any keybinds

**Expected behavior**
Some reaction to the Control keys and Meta keys

**Versions (please complete the following info):**
 - Distro and DE/WM: Devuan with i3-gaps
 - Versions of Dependencies: Whatever's in the Debian repos
 - M-x emacs-version: GNU Emacs 26.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.5) of 2019-09-22, modified by Debian

**Screenshots**

**Additional context**
I have EVIL on the system, but even if I force it to load with the EMACS keybindings or use the EVIL package, no keybinding works

**Comment by MatthewZMD** [comment] 2020-09-27 04:55
Duplicate of #237 

Unfortunately it doesn't support i3 properly at the moment, anyone with the knowledge is welcome to contribute.

**Closed by MatthewZMD** 2020-09-27 04:55 UTC
