### ISSUE TITLE
EAF breaks after update

### ISSUE THREAD

**Issue by dalanicolai** [manateelazycat/emacs-application-framework#641] opened 2021-04-27 07:59 UTC
EAF was working fine until today's update

- Please check the `*eaf*` buffer, if there is any error shown in the `*eaf*` buffer, paste it here.
```
EAF process starting...
Traceback (most recent call last):
  File "/home/dalanicolai/spacemacs/elpa/28.0/develop/eaf-20210426.1505/core/utils.py", line 58, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/home/dalanicolai/spacemacs/elpa/28.0/develop/eaf-20210426.1505/eaf.py", line 133, in new_buffer
    self.create_app(buffer_id, str(url), "app.{0}.buffer".format(str(app_name)), str(arguments))
  File "/home/dalanicolai/spacemacs/elpa/28.0/develop/eaf-20210426.1505/eaf.py", line 180, in create_app
    self.create_buffer(buffer_id, url, module_path, arguments)
  File "/home/dalanicolai/spacemacs/elpa/28.0/develop/eaf-20210426.1505/eaf.py", line 194, in create_buffer
    app_buffer = module.AppBuffer(buffer_id, url, eaf_config_dir, arguments, self.emacs_var_dict, module_path)
  File "/home/dalanicolai/spacemacs/elpa/28.0/develop/eaf-20210426.1505/app/browser/buffer.py", line 35, in __init__
    BrowserBuffer.__init__(self, buffer_id, url, config_dir, arguments, emacs_var_dict, module_path, False)
  File "/home/dalanicolai/spacemacs/elpa/28.0/develop/eaf-20210426.1505/core/browser.py", line 612, in __init__
    self.add_widget(BrowserView(buffer_id, config_dir))
  File "/home/dalanicolai/spacemacs/elpa/28.0/develop/eaf-20210426.1505/core/browser.py", line 71, in __init__
    self.dark_mode_js = open(os.path.join(os.path.dirname(os.path.dirname(__file__)),
FileNotFoundError: [Errno 2] No such file or directory: '/home/dalanicolai/spacemacs/elpa/28.0/develop/eaf-20210426.1505/node_modules/darkreader/darkreader.js'
Traceback (most recent call last):
  File "/home/dalanicolai/spacemacs/elpa/28.0/develop/eaf-20210426.1505/core/utils.py", line 58, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/home/dalanicolai/spacemacs/elpa/28.0/develop/eaf-20210426.1505/eaf.py", line 256, in update_views
    view = View(self.buffer_dict[buffer_id], view_info)
KeyError: 'f354-5df2-7ef0-230a-f79e-2b87-7e2b'

Process *eaf* aborted (core dumped)
```

**Describe the bug**
After today's update eaf hangs while trying to open any page. It works correctly when I rollback (using Spacemacs rollback feature) to EAF version of 15th of april

**To Reproduce**
Just try to open any page

**Expected behavior**
Page opens noramlly like before the update

**Versions (please complete the following info):**
 - Fedora with KDE on Wayland
 - M-x emacs-version:  GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.25, cairo version 1.16.0) of 2021-02-18

**Comment by MatthewZMD** [comment] 2021-04-27 21:27
Hmmm, seems like the node_modules are gone after the update for some reason, it should be fixed if you run npm install again.

**Comment by manateelazycat** [comment] 2021-04-28 00:51
You should run install-eaf.sh to install all nodejs depends.

Or just execute command ```npm install``` in root directory of EAF project.

**Closed by manateelazycat** 2021-04-28 00:51 UTC

**Comment by MatthewZMD** [comment] 2021-04-28 03:13
The problem is more like why did the node_modules got removed with a package update.

What is the package manager that's used?
